'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import OrganScene from '../components/OrganScene';
import {api,ModelInfo,Prediction,BatchResult} from '../lib/api';
import {Activity,ArrowRight,BrainCircuit,CheckCircle2,ChevronRight,Download,Layers3,Microscope,RefreshCw,ShieldCheck,Upload,Wifi,ScanLine} from 'lucide-react';

export default function Home(){
 const [models,setModels]=useState<ModelInfo[]>([]),[model,setModel]=useState('resnet50'),[health,setHealth]=useState<any>(null),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[result,setResult]=useState<Prediction|null>(null),[batch,setBatch]=useState<BatchResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[view,setView]=useState<'home'|'analyze'>('home');
 const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{Promise.all([api.models(),api.health()]).then(([m,h])=>{setModels(m.models);setModel(m.default_model);setHealth(h)}).catch(e=>setError(e.message))},[]);
 const selectFile=(f:File)=>{setFile(f);setPreview(URL.createObjectURL(f));setResult(null);setError('');setView('analyze')};
 const run=async()=>{if(!file)return;setBusy(true);setError('');try{setResult(await api.predict(file,model,true))}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const confidence=result?Math.round(result.confidence*100):0; const probability=result?Math.round(result.probability*100):0;
 const report=result?api.reportUrl(result):'';
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span className="brand-mark"><Activity size={18}/></span><span><b>PANCREA</b><small>CLINICAL AI LAB</small></span></a><nav><a href="#technology">Technology</a><a href="#workbench">Workbench</a><a href="#xai">Explainability</a></nav><button className="status"><span className="dot"/> {health?.status==='healthy'?'SYSTEM ONLINE':'CONNECTING'}</button></header>
  {view==='home'&&<>
  <section className="hero" id="top"><div className="hero-copy"><div className="eyebrow"><ScanLine size={14}/> CT INTELLIGENCE / TRANSFER LEARNING</div><h1>See what the model <em>sees.</em></h1><p>Pancreatic CT analysis built around transfer learning, localized explainability, and a radiology-inspired review workflow.</p><div className="hero-actions"><button className="primary" onClick={()=>setView('analyze')}>Open imaging workbench <ArrowRight size={17}/></button><a className="text-link" href="#technology">Explore the pipeline <ChevronRight size={15}/></a></div><div className="hero-metrics"><span><b>06</b> registered backbones</span><span><b>Grad-CAM++</b> lesion localization</span><span><b>API</b> live inference</span></div></div><OrganScene/></section>
  <section className="signal-strip"><div><small>MODEL RUNTIME</small><strong>{health?.loaded_models?.length||0} checkpoint{(health?.loaded_models?.length||0)!==1?'s':''} available</strong></div><div><small>ACCELERATOR</small><strong>{health?.gpu_available?'GPU detected':'CPU inference'}</strong></div><div><small>INPUT</small><strong>PNG · JPEG · CT slice</strong></div><div><small>EXPLAINABILITY</small><strong>Grad-CAM++</strong></div></section>
  <section className="section" id="technology"><div className="section-kicker">THE PIPELINE</div><h2>From CT slice to interpretable signal.</h2><div className="pipeline"><article><span>01</span><Microscope/><h3>Normalize</h3><p>Prepare abdominal CT imagery for the selected vision backbone.</p></article><article><span>02</span><BrainCircuit/><h3>Infer</h3><p>Run transfer-learning classification through the FastAPI model layer.</p></article><article><span>03</span><Layers3/><h3>Explain</h3><p>Overlay Grad-CAM++ activations and surface suspicious regions.</p></article></div></section>
  <section className="xai-section" id="xai"><div><div className="section-kicker">EXPLAINABLE AI</div><h2>Confidence is useful.<br/><em>Evidence is better.</em></h2><p>The interface keeps the prediction beside the scan and its activation map, so the model output remains inspectable instead of becoming a black-box number.</p></div><div className="xai-card"><div className="fake-scan"><div className="crosshair"/><div className="heat heat-a"/><div className="heat heat-b"/><span>ACTIVATION FIELD</span></div><div className="xai-legend"><span><i/>low activation</span><span><i/>high activation</span></div></div></section>
  </>}
  <section className={`workbench ${view==='analyze'?'visible':''}`} id="workbench"><div className="work-head"><div><div className="section-kicker">IMAGING WORKBENCH</div><h2>Analyze a CT slice</h2></div><button className="ghost" onClick={()=>{setView('home');setFile(null);setResult(null)}}>Back to overview</button></div>
   <div className="work-grid"><aside className="control-panel"><div className="panel-title">Scan input</div><button className="dropzone" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)selectFile(f)}}><Upload size={22}/><b>{file?file.name:'Drop CT slice here'}</b><small>PNG or JPEG · up to backend limit</small><input ref={input} hidden type="file" accept="image/png,image/jpeg" onChange={e=>e.target.files?.[0]&&selectFile(e.target.files[0])}/></button>
   <label className="field"><span>Transfer-learning model</span><select value={model} onChange={e=>setModel(e.target.value)}>{models.map(m=><option key={m.name} value={m.name}>{m.display_name}</option>)}</select></label>
   <div className="model-note"><span className="live-dot"/> {models.find(m=>m.name===model)?.description||'Loading model metadata…'}</div>
   <button className="primary full" disabled={!file||busy} onClick={run}>{busy?<><RefreshCw className="spin" size={17}/>Analyzing scan…</>:<>Run AI analysis <ArrowRight size={17}/></>}</button>
   <div className="safety"><ShieldCheck size={17}/><span><b>Research workflow</b> Output is decision support, not a standalone diagnosis.</span></div>
   </aside>
   <section className="viewer"><div className="viewer-toolbar"><span>CT / AXIAL</span><span>{result?`INFERENCE · ${result.inference_time_ms} ms`:'WAITING FOR SCAN'}</span></div><div className="scan-view">{preview?<><img src={result?.heatmap_base64?`data:image/jpeg;base64,${result.heatmap_base64}`:preview} alt="Uploaded CT scan or Grad-CAM overlay"/><div className="viewer-grid"/></>:<div className="empty-view"><ScanLine size={38}/><b>CT viewport ready</b><span>Upload a slice to begin analysis.</span></div>}{result?.bounding_boxes?.map((b,i)=><div key={i} className="bbox" style={{left:`${b.x}px`,top:`${b.y}px`,width:`${b.width}px`,height:`${b.height}px`}}/> )}</div><div className="viewer-footer"><span>HU WINDOW · PANCREATIC</span><span>GRAD-CAM++ {result?'AVAILABLE':'STANDBY'}</span></div></section>
   <aside className="results-panel"><div className="panel-title">AI analysis</div>{result?<><div className={`verdict ${result.is_cancerous?'alert':'clear'}`}><span>{result.is_cancerous?'POSITIVE INDICATION':'NO CANCEROUS SIGNAL'}</span><b>{probability}%</b><small>malignancy probability</small></div><div className="score"><div><span>Confidence</span><b>{confidence}%</b></div><div className="meter"><i style={{width:`${confidence}%`}}/></div></div><div className="result-list"><div><span>Model</span><b>{result.model_used.toUpperCase()}</b></div><div><span>Threshold</span><b>{result.optimal_threshold}</b></div><div><span>Lesion regions</span><b>{result.bounding_boxes.length}</b></div></div><a className="report" href={report}><Download size={16}/> Generate clinical PDF</a></>:<div className="results-empty"><Activity size={24}/><b>Awaiting inference</b><span>Prediction, confidence and explainability data will appear here.</span></div>}</aside></div>
   {error&&<div className="error">{error}</div>}
  </section>
  <footer><div><b>PANCREA</b> · Pancreatic Cancer Detection Using Transfer Learning</div><span>Research / educational system · Not FDA approved</span></footer>
 </main>
}
